[package]
name = "aw-upscale-server"
version = "0.1.0"
edition = "2021"
description = "A server to run upscaling on another machine"
readme = "README.md"
license = "MIT"
keywords = ["waifu2x"]
homepage = "https://github.com/awused/aw-upscale/server"
repository = "https://github.com/awused/aw-upscale/server"


[dependencies]
aw-upscale = { path = ".." }
clap = { version = "3.1.10", features = ["derive"] }
futures = "0.3.21"
once_cell = "1.10.0"
prost = "0.10.1"
prost-types = "0.10.1"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["fs", "net", "macros", "process", "rt", "rt-multi-thread", "sync"] }
tonic = "0.7.1"

[build-dependencies]
tonic-build = "0.7.0"
prost-build = "0.10.1"
