[package]
name = "aw-upscale-server"
version = "0.1.0"
edition = "2021"
description = "A server to run upscaling on another machine"
readme = "README.md"
license = "MIT"
keywords = ["waifu2x"]
homepage = "https://github.com/awused/aw-upscale/server"
repository = "https://github.com/awused/aw-upscale/server"


[dependencies]
aw-upscale = { path = ".." }
clap = { version = "4.5.4", features = ["derive"] }
futures = { version = "0.3.30", default-features = false }
once_cell = "1.19.0"
prost = { version = "0.12.6", default-features = false, features = ["std"] }
prost-types = "0.12.6"
tempfile = "3.10.1"
tokio = { version = "1.38.0", features = ["fs", "net", "macros", "process", "rt", "rt-multi-thread", "sync"] }
tonic = "0.11.0"

[build-dependencies]
tonic-build = "0.11.0"
prost-build = "0.12.6"
