[package]
name = "aw-upscale-server"
version = "0.1.0"
edition = "2021"
description = "A server to run upscaling on another machine"
readme = "README.md"
license = "MIT"
keywords = ["waifu2x"]
homepage = "https://github.com/awused/aw-upscale/server"
repository = "https://github.com/awused/aw-upscale/server"


[dependencies]
aw-upscale = { path = ".." }
clap = { version = "4.0.10", features = ["derive"] }
futures = { version = "0.3.24", default-features = false }
once_cell = "1.15.0"
prost = { version = "0.11.0", default-features = false, features = ["std"] }
prost-types = "0.11.1"
tempfile = "3.3.0"
tokio = { version = "1.21.2", features = ["fs", "net", "macros", "process", "rt", "rt-multi-thread", "sync"] }
tonic = "0.8.2"

[build-dependencies]
tonic-build = "0.8.2"
prost-build = "0.11.1"
