[package]
name = "aw-upscale-server"
version = "0.1.0"
edition = "2021"
description = "A server to run upscaling on another machine"
readme = "README.md"
license = "MIT"
keywords = ["waifu2x"]
homepage = "https://github.com/awused/aw-upscale/server"
repository = "https://github.com/awused/aw-upscale/server"


[dependencies]
aw-upscale = { path = ".." }
futures = "0.3.17"
once_cell = "1.8.0"
prost = "0.9.0"
structopt = "0.3.25"
tempfile = "3.2.0"
tokio = { version = "1.13.0", features = ["fs", "net", "macros", "process", "rt", "rt-multi-thread", "sync"] }
tonic = "0.6.1"

[build-dependencies]
tonic-build = "0.6.0"
