[package]
name = "aw-upscale-server"
version = "0.1.0"
edition = "2021"
description = "A server to run upscaling on another machine"
readme = "README.md"
license = "MIT"
keywords = ["waifu2x"]
homepage = "https://github.com/awused/aw-upscale/server"
repository = "https://github.com/awused/aw-upscale/server"


[dependencies]
aw-upscale = { path = ".." }
clap = { version = "4.1.8", features = ["derive"] }
futures = { version = "0.3.26", default-features = false }
once_cell = "1.17.1"
prost = { version = "0.11.8", default-features = false, features = ["std"] }
prost-types = "0.11.8"
tempfile = "3.4.0"
tokio = { version = "1.26.0", features = ["fs", "net", "macros", "process", "rt", "rt-multi-thread", "sync"] }
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8.4"
prost-build = "0.11.8"
