# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upscale.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rupscale.proto\x12\x07upscale\x1a\x1egoogle/protobuf/duration.proto\"+\n\nResolution\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\"X\n\x0bResolutions\x12#\n\x06target\x18\x01 \x01(\x0b\x32\x13.upscale.Resolution\x12$\n\x07minimum\x18\x02 \x01(\x0b\x32\x13.upscale.Resolution\"\xfc\x01\n\x0eUpscaleRequest\x12\x0f\n\x05scale\x18\x01 \x01(\rH\x00\x12+\n\x0bresolutions\x18\x02 \x01(\x0b\x32\x14.upscale.ResolutionsH\x00\x12\x11\n\x07nothing\x18\x06 \x01(\rH\x00\x12\x14\n\x07\x64\x65noise\x18\x03 \x01(\x11H\x01\x88\x01\x01\x12\x15\n\roriginal_file\x18\x04 \x01(\x0c\x12\x14\n\x0coriginal_ext\x18\x05 \x01(\t\x12/\n\x07timeout\x18\x07 \x01(\x0b\x32\x19.google.protobuf.DurationH\x02\x88\x01\x01\x42\r\n\x0btarget_sizeB\n\n\x08_denoiseB\n\n\x08_timeout\"E\n\x0fUpscaleResponse\x12 \n\x03res\x18\x01 \x01(\x0b\x32\x13.upscale.Resolution\x12\x10\n\x08upscaled\x18\x02 \x01(\x0c\x32K\n\tAwUpscale\x12>\n\x07Upscale\x12\x17.upscale.UpscaleRequest\x1a\x18.upscale.UpscaleResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upscale_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESOLUTION._serialized_start=58
  _RESOLUTION._serialized_end=101
  _RESOLUTIONS._serialized_start=103
  _RESOLUTIONS._serialized_end=191
  _UPSCALEREQUEST._serialized_start=194
  _UPSCALEREQUEST._serialized_end=446
  _UPSCALERESPONSE._serialized_start=448
  _UPSCALERESPONSE._serialized_end=517
  _AWUPSCALE._serialized_start=519
  _AWUPSCALE._serialized_end=594
# @@protoc_insertion_point(module_scope)
