# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import upscale_pb2 as upscale__pb2


class AwUpscaleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upscale = channel.unary_unary(
                '/upscale.AwUpscale/Upscale',
                request_serializer=upscale__pb2.UpscaleRequest.SerializeToString,
                response_deserializer=upscale__pb2.UpscaleResponse.FromString,
                )


class AwUpscaleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upscale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AwUpscaleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upscale': grpc.unary_unary_rpc_method_handler(
                    servicer.Upscale,
                    request_deserializer=upscale__pb2.UpscaleRequest.FromString,
                    response_serializer=upscale__pb2.UpscaleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upscale.AwUpscale', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AwUpscale(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upscale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/upscale.AwUpscale/Upscale',
            upscale__pb2.UpscaleRequest.SerializeToString,
            upscale__pb2.UpscaleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
